jwtk/jjwt

pom.xml
I have tested jjwt as bundle in Equinox Kepler SR1 and it is completely okay! Bundle is resolved:
59      RESOLVED    io.jsonwebtoken.jjwt_0.5.0.SNAPSHOT
This code:
byte[] key = new byte[64];
new SecureRandom().nextBytes(key);
String compact = Jwts.builder().setSubject("Joe").signWith(SignatureAlgorithm.HS256, key).compact();
if (Jwts.parser().setSigningKey(key).parseClaimsJws(compact).getBody().getSubject().equals("Joe")) {
System.out.println("Jjwt is okay");
}
And it prints as expected:
Jjwt is okay
In continue of https://github.com/jwtk/jjwt/issues/19
=> add osgi support via maven-bundle-plugin

src/test/groovy/io/jsonwebtoken/JwtParserTest.groovy
- Fixed broken test
- added in fail() statements inside each try that was missing one
=> Jwt parser test fix

.travis.yml
Resolves #97 
Oracle JDK 7 works fine and JDK 7 is end-of-life anyway
=> Removed openjdk7 from travis build.

pom.xml
Changed the packaging type to bundle - required
by the bundle plugin.
Upgraded to the latest version of the maven
bundle plugin.
=> Made the android dep optional in OSGi

src/main/java/io/jsonwebtoken/impl/DefaultJwtParser.java
Quite possible we're missing something here, so please forgive if so. After seeing [this article](https://auth0.com/blog/2015/03/31/critical-vulnerabilities-in-json-web-token-libraries/) (see "RSA or HMAC?" section), we did a quick scan through the JJWT implementation to see if it was vulnerable. While it seems like the RSA check should work, no such check seemed to exist for ECDSA signatures.
As a result, it may be possible for users of this library to use `setSigningKey(byte[] key)` while intending to use ECDSA, but have the client alter the algorithm and signature to use HMAC with the public key as the "secret key", allowing the client to inject arbitrary payloads.
cc @thomaso-mirodin
=> Avoid potentially critical vulnerability in ECDSA signature validation

README.md
Resolves issue #149: the NIST `P-521` curve is misnamed as `P-512` in the `ES512` JWS algorithm description in the README.
Reference: the [RFC on ECC in TLS](https://tools.ietf.org/html/rfc4492#appendix-A).
=> Fix ES512 description typo in README

src/main/java/io/jsonwebtoken/impl/DefaultJwtParser.java, src/main/java/io/jsonwebtoken/lang/Strings.java, src/test/groovy/io/jsonwebtoken/lang/StringsTest.groovy
re-use buffer instead of creating new ones
avoid creating unneeded buffers in the Strings util methods
Stop continuously copying array with StringBuilder#deleteCharAt
work directly on StringBuilder instead of creating a temporary String
test added to cover the modified methods
=> improve jwt parser memory allocation

src/main/java/io/jsonwebtoken/JwtParser.java, src/main/java/io/jsonwebtoken/impl/DefaultJwtParser.java, src/test/groovy/io/jsonwebtoken/JwtParserTest.groovy
I realize there is an existing pull request that references this issue, but it combines an implementation for the issue with another related but separate one. Thought there might be some value in having one that addresses this issue directly as an alternative. (This is my first pull request, my apologies if I've unwittingly committed a faux pas.)
=> #61: Add support for clock skew to JwtParser for exp and nbf claims

src/main/java/io/jsonwebtoken/impl/DefaultClaims.java, src/test/groovy/io/jsonwebtoken/JwtParserTest.groovy, src/test/groovy/io/jsonwebtoken/impl/DefaultClaimsTest.groovy
Jackson chooses the target type for JSON numbers based on their value,
while deserializing without correct typing information present.
This leads to a confusing behavior:
String token = Jwts.builder()
.claim("byte", (byte) 42)
.claim("short", (short) 42)
.claim("int", 42)
.claim("long_small", (long) 42)
.claim("long_big", ((long) Integer.MAX_VALUE) + 42)
.compact();
Claims claims = (Claims) Jwts.parser().parse(token).getBody();
claims.get("int", Integer.class); // => 42
claims.get("long_big", Long.class); // => ((long) Integer.MAX_VALUE) + 42
claims.get("long_small", Long.class); // throws RequiredTypeException: required=Long, found=Integer
claims.get("short", Short.class); // throws RequiredTypeException: required=Short, found=Integer
claims.get("byte", Byte.class); // throws …
=> Implement type conversions of integral claim values

src/main/java/io/jsonwebtoken/JwtBuilder.java, src/main/java/io/jsonwebtoken/impl/DefaultJwtBuilder.java, src/test/groovy/io/jsonwebtoken/impl/DefaultJwtBuilderTest.groovy
This function does not overwrite existing claims (as compared to setClaims). See Issue #196
=> Added addClaims function to JwtBuilder as described in Issue #196.

src/main/java/io/jsonwebtoken/impl/crypto/EllipticCurveSigner.java, src/test/groovy/io/jsonwebtoken/impl/crypto/EllipticCurveSignerTest.groovy
Similar to issue #68  (https://github.com/jwtk/jjwt/issues/68), EC keys on Android do not implement ECPrivateKey.  This changes the check in EllipticCurveSigner.java to use the same test as was used to solve issue #68 for RSA keys.
=> Test for instanceof PrivateKey and instanceof ECKey when signing

.travis.yml, pom.xml, src/main/java/io/jsonwebtoken/Claims.java, src/main/java/io/jsonwebtoken/CompressionCodecs.java, src/main/java/io/jsonwebtoken/Header.java, src/main/java/io/jsonwebtoken/JwtBuilder.java, src/main/java/io/jsonwebtoken/JwtParser.java, src/main/java/io/jsonwebtoken/SignatureAlgorithm.java, src/main/java/io/jsonwebtoken/SigningKeyResolver.java, src/main/java/io/jsonwebtoken/impl/crypto/MacProvider.java, src/main/java/io/jsonwebtoken/lang/Strings.java
Fixes #259 
Added support for Java 9 build and test run. Does not impact Java 8 build and test. 
Overrode some OSS version dependency version defaults to support Java 9. 
Updated javadocs in code to pass java 9 linter.
Added Java 9 build to Travis file.
=> Support java 9

pom.xml
The MANIFEST.MF contains an Implementation-URL key, that comes from
project.url if defined. If not defined, jjwt's url comes from sonatype
which seems to falsely associate it with a sonatype/nexus CVE and
fails the project build.
https://github.com/jwtk/jjwt/issues/234
=> Add project.url to satisfy the dependency-check-maven plugin

README.md, pom.xml
* Updates jackson-databind version to 2.8.11.1 to fix CVE-2017-17485
Signed-off-by: John Bard <jbard@vmware.com>
=> closes #302: Update jackson version

src/test/groovy/io/jsonwebtoken/codec/impl/Base64Test.groovy
* Adds test vector to base64 & base64url for many ascii chars
Signed-off-by: Ryan Bard <john.ryan.bard@gmail.com>
=> tests #333: Add ascii base64 test vector

pom.xml
Fixed master branch pom project version - it should always be a Maj.min.0-SNAPSHOT version.
=> Fix master branch pom project version

pom.xml
Upgraded bouncycastle to the latest stable 1.60 release.
Resolves #353
=> Upgrade BouncyCastle to 1.60

api/src/main/java/io/jsonwebtoken/JwtBuilder.java, api/src/main/java/io/jsonwebtoken/SignatureAlgorithm.java, api/src/main/java/io/jsonwebtoken/security/Keys.java, api/src/test/groovy/io/jsonwebtoken/SignatureAlgorithmTest.groovy, api/src/test/groovy/io/jsonwebtoken/security/KeysTest.groovy, impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtBuilder.java, impl/src/test/groovy/io/jsonwebtoken/JwtParserTest.groovy, impl/src/test/groovy/io/jsonwebtoken/JwtsTest.groovy, impl/src/test/groovy/io/jsonwebtoken/RsaSigningKeyResolverAdapterTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtBuilderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtParserTest.groovy
Added JwtBuilder#signWith(Key) with tests and refactoring.  Deprecated additional signWith methods that can lead to confusion.  Resolves #366
=> Added JwtBuilder#signWith(Key) with tests and refactoring.

.travis.yml, api/src/main/java/io/jsonwebtoken/JwtBuilder.java, pom.xml
Enabled maven profile for JDK >= 9 that will add a surefire `<argLine>` with `--add-opens java.base/jdk.internal.loader=ALL-UNNAMED` to ensure module reflection can occur during tests.  Resolves #364
=> Re-enable builds on JDK 9+

.travis.yml, CHANGELOG.md, README.md, api/pom.xml, api/src/main/java/io/jsonwebtoken/SignatureAlgorithm.java, api/src/test/groovy/io/jsonwebtoken/JwtsTest.groovy, api/src/test/groovy/io/jsonwebtoken/SignatureAlgorithmTest.groovy, extensions/jackson/pom.xml, extensions/orgjson/pom.xml, extensions/pom.xml, impl/pom.xml, impl/src/main/java/io/jsonwebtoken/impl/crypto/EllipticCurveProvider.java, impl/src/main/java/io/jsonwebtoken/impl/crypto/RsaProvider.java, impl/src/test/groovy/io/jsonwebtoken/impl/crypto/EllipticCurveProviderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/crypto/EllipticCurveSignatureValidatorTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/crypto/SignatureProviderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/security/KeysImplTest.groovy, pom.xml
Ensured BouncyCastle was optional.  Also ensured EllipticCurve algorithms could be used without BouncyCastle since the JDK supports EC by default.  Moved `RuntimeEnvironment.enableBouncyCastleIfPossible()` call out of `SignatureAlgorithm` into `RsaProvider` since BC is only necessary for RSASSA-PSS algorithms (PS256, PS384, PS512) and nothing else in JJWT's codebase.
Resolves #372
=> Ensure BouncyCastle is optional

api/src/main/java/io/jsonwebtoken/JwtBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultClaims.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/JwtMap.java
fixes #84
This would allow to pass `Map<String,String>`
=> #84 JwtBuilder.setClaims() now accepts `Map<String, ?> claims`

.travis.yml, api/src/test/groovy/io/jsonwebtoken/SignatureAlgorithmTest.groovy, pom.xml
There were a couple issues preventing running the build with Java 11
- A groovy bug - fixed with a version bump https://issues.apache.org/jira/browse/GROOVY-8727
- The ASM version that is embedded in easymock does NOT support Java 11 classes - worked around by stubbing out those usages instead
- javadoc modules issue - fixed by setting the Javadoc source version to 1.7
=> Add support for testing with JDK11

CHANGELOG.md, api/src/main/java/io/jsonwebtoken/Claims.java, api/src/main/java/io/jsonwebtoken/lang/Maps.java, api/src/test/groovy/io/jsonwebtoken/lang/MapsTest.groovy, extensions/jackson/src/main/java/io/jsonwebtoken/jackson/io/JacksonDeserializer.java, extensions/jackson/src/test/groovy/io/jsonwebtoken/jackson/io/JacksonDeserializerTest.groovy, extensions/jackson/src/test/groovy/io/jsonwebtoken/jackson/io/JacksonSerializerTest.groovy, extensions/jackson/src/test/groovy/io/jsonwebtoken/jackson/io/stubs/CustomBean.groovy, impl/src/main/java/io/jsonwebtoken/impl/DefaultClaims.java, impl/src/test/groovy/io/jsonwebtoken/CustomObjectDeserializationTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultClaimsTest.groovy
Adds new constructor to `JacksonDeserializer(Map<String, Class>
claimTypeMap)`, which will enable later calls `Claims.get("key",
CustomType.class)` to work as expectd
Fixes: #369
TODO:
=> Add support for custom type deserialization with Jackson

extensions/jackson/src/main/java/io/jsonwebtoken/jackson/io/JacksonDeserializer.java
=> Fix minor Javadoc error in JacksonDeserializer

impl/src/main/java/io/jsonwebtoken/impl/compression/DeflateCompressionCodec.java, impl/src/test/groovy/io/jsonwebtoken/impl/compression/DeflateCompressionCodecTest.groovy
if encountering an IOException.  This allows compressed JWTs created before 0.10.7 to still work in 0.10.8 and later.  Fixes #536
=> Ensured DeflateCompressionCodec could fallback to <= 0.10.6 implementation

CHANGELOG.md, README.md
Fixes #410 
Because this represents public facing documentation, it can only be merged to master immediately prior to the 0.11.0 release (otherwise people will see Gson documentation in master and wonder why it's not in the 0.10.7 artifacts).
=> Updated documentation and changelog to reflect the new Gson extension

README.md
=> Documented why changing Base64 sometimes does not invalid signature checks.

CHANGELOG.md, README.md, api/src/main/java/io/jsonwebtoken/JwtParserBuilder.java, api/src/main/java/io/jsonwebtoken/Jwts.java
- Update README to use `parserBuilder()` instead of `parser()` (#499)
- Docs: Adds section to README covering custom object parsing (#500)
- Docs: Add note about JwtParserBuilder creating an immutable JwtParser (#508)
Doc: #486
Fixes: #494
Doc: #495
Fixes: #171
=> README edits for 0.11.0

CHANGELOG.md, extensions/jackson/src/main/java/io/jsonwebtoken/jackson/io/JacksonDeserializer.java, extensions/jackson/src/test/groovy/io/jsonwebtoken/jackson/io/JacksonDeserializerTest.groovy
and other maps that do NOT allow null keys
=> Allow JacksonDeserializer to work with Java 9+ Map.of

CHANGELOG.md, api/src/main/java/io/jsonwebtoken/lang/Classes.java, impl/src/main/java/io/jsonwebtoken/impl/lang/Services.java, impl/src/test/groovy/io/jsonwebtoken/impl/lang/ServicesTest.groovy
Services are now loaded from the context class loader, Services.class.classLoader, and the system classloader, the first classloader with a service wins, and the others are ignored. This mimics how `Classes.forName()` works, and how JJWT attempted to auto-discover various implementations in previous versions.
Fixes: #568
=> Services now checks the contextClassLoader, Services.class.classLoader, and the system classloader

api/src/main/java/io/jsonwebtoken/SignatureAlgorithm.java, api/src/test/groovy/io/jsonwebtoken/SignatureAlgorithmTest.groovy
Hello,
This is a first draft for jwtk/jjwt#588
I've added the OIDs for Hmac-Keys and extended the check in the assertValid method. There are multiple ways of doing this, I decided to extend the SignatureAlgorithm's constructor with a varargs parameter to avoid having to modify all enum values.
For the test, an actual pkcs12 KeyStore instance is used to store and load the key. I suppose, one could mock the key. Would that be necessary?
The coverage checks failed to upload in my cloned repository, I suppose they will successfully do so, when the pr is built.
=> Accept oid in assertValid

extensions/gson/src/main/java/io/jsonwebtoken/gson/io/GsonDeserializer.java
Hello,
in this piece of code:
```java
protected T readValue(byte[] bytes) throws IOException {
return gson.fromJson(new String(bytes), returnType);
}
```
`new String(bytes)` will use system default Charset, while `UTF-8` should be used according to JWT RFC: https://tools.ietf.org/html/rfc7519#section-7.2
So, if JVM was started with "`-Dfile.encoding=ISO-8859-1`" system property then `GsonDeserializer` corrupts data during deserialization:
=> Always use UTF-8 in GsonDeserializer

.travis.yml, pom.xml
Hi,
I've noticed, that jjwt tests fail in JDK14 because of [GROOVY-9211]. I've taken the liberty to add openjdk14 as a build in travis configuration and bumped the groovy version to 2.5.11, where the issue is fixed.
[GROOVY-9211]: https://issues.apache.org/jira/browse/GROOVY-9211
=> Add support for jdk14

api/src/main/java/io/jsonwebtoken/JwtParser.java, api/src/main/java/io/jsonwebtoken/JwtParserBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParser.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParserBuilder.java, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtParserBuilderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtParserTest.groovy
Ensured setting allowedClockSkewSeconds to be greater than (Long.MAX_VALUE / 1000) will throw an IllegalArgumentException.
Resolves #583
=> Argument validation for allowedClockSkewSeconds

.travis.yml
The previously used URL is dead, which was preventing other PRs from passing CI
=> Updates the Java 7 install location for CI

pom.xml
NOTE: This fork supports Clover for test coverage
=> Update fork of coverall-maven-plugin fork

CHANGELOG.md, impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParser.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParserBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/JwtDeserializer.java, impl/src/test/groovy/io/jsonwebtoken/DeprecatedJwtParserTest.groovy, impl/src/test/groovy/io/jsonwebtoken/JwtParserTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtParserBuilderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtParserTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/JwtDeserializerTest.groovy
Move the parser error handling logic out of DefaultJwtParser into the new JwtDeserializer and wraps them with developer freiendly exceptions
Add check for common JSON parsing exceptions like stack overflow when parsing deeply nested (or malformed) JSON
=> Adds handling for common JSON parsing exceptions and wraps them in a `JwtException`

README.md
Just reading through the doc trying to learn how to use it, and found a typo I think.
the resulting string **NOT is** safe to expose publicly => the resulting string **is NOT** safe to expose publicly
=> fix: typo in the README

.lift/config.toml
Following up on the conversation in #690, this is a Sonatype Lift configuration if desired. It's an automation of many tools including Cobra, Semgrep, FindSecBugs, Infer, and Errorprone.  The [app is here](https://github.com/apps/sonatype-lift) and the [marketplace is there](https://github.com/marketplace/muse-dev).
=> Add a Sonatype Lift configuration to ignore uninteresting results

impl/src/main/java/io/jsonwebtoken/impl/JwtMap.java
Found via infer on Lift, an inefficient keyset iterator is in the form:
```
for key in mapping:
entry = mapping.find(key)
```
Which is linear-log instead of the more optimal linear solution.
N.B. This commit bundles in the Lift configuration (i.e. https://github.com/marketplace/muse-dev) used when this bug was found. If you install the app then depending on the preferences, we might want to add some of the other observed issue types to an ignore list.
=> Fix an inefficient keyset iterator

pom.xml
This is important to get the latest security fixes from jackson.
Users of jjwt-jackson have to exclude and manually upgrade this dependency otherwise.
=> Bump jackson dependency to latest

README.md
Using the outdated configurations `compile` and `runtime` like in README.md leads to gradle errors which are not trivial to understand.
Quoting [from StackOverflow](https://stackoverflow.com/a/66910991/39946):
> Note that the `compile`, `runtime`, `testCompile`, and `testRuntime`
> configurations introduced by the Java plugin have been deprecated
> since [Gradle 4.10][1] ([Aug 27, 2018][2]), and were finally removed
> in [Gradle 7.0][3] ([Apr 9, 2021][2]).
> 
> The aforementioned configurations should be replaced by
> `implementation`, `runtimeOnly`, `testImplementation`, and
> `testRuntimeOnly`, respectively.
I don't think that a special note for users of gradle below version 4.10 is needed.
[1]: https://docs.gradle.org/4.10/userguide/java_plugin.html#sec:java_plugin_and_dependency_manage …
=> Update gradle dependencies in README.md

api/src/main/java/io/jsonwebtoken/HeaderMutator.java, api/src/main/java/io/jsonwebtoken/JwtBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultHeader.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/lang/CompactMediaTypeIdConverter.java, impl/src/test/groovy/io/jsonwebtoken/JwtsTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultHeaderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtHeaderBuilderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/lang/CompactMediaTypeIdConverterTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/RFC7520Section5Test.groovy
Ensured header `cty` raw value reflects a compact form but `getContentType()` return value reflects a normalized value per per https://www.rfc-editor.org/rfc/rfc7515.html#section-4.1.10
=> Automatic compact `cty` header

README.md, impl/pom.xml, impl/src/test/groovy/io/jsonwebtoken/impl/security/Pkcs11Test.groovy, pom.xml, tdjar/pom.xml
Upgraded BC to 1.76
Also addressed Pkcs11Test that fails on Mac OS (arm64) with JDK 1.7 (x86_64)
=> Upgrade BC to 1.76

README.md, impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParser.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParserBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/security/AbstractSecureDigestAlgorithm.java, impl/src/main/java/io/jsonwebtoken/impl/security/DefaultMacAlgorithm.java, impl/src/main/java/io/jsonwebtoken/impl/security/RsaSignatureAlgorithm.java, impl/src/test/groovy/io/jsonwebtoken/JwtsTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/AbstractSecureDigestAlgorithmTest.groovy, impl/src/test/groovy/io/jsonwebtoken/issues/Issue365Test.groovy
Closes #365 
* Added regression tests
* Removed default doDigest implementation from AbstractSecureDigestAlgorithm and put it in DefaultMacAlgorithm (where it should have been) since SignatureAlgorithms override it already
=> Added regression tests for #365

README.md, api/src/main/java/io/jsonwebtoken/Claims.java, api/src/main/java/io/jsonwebtoken/ClaimsMutator.java, api/src/main/java/io/jsonwebtoken/JwtParserBuilder.java, api/src/main/java/io/jsonwebtoken/lang/Collections.java, api/src/main/java/io/jsonwebtoken/security/PrivateKeyBuilder.java, api/src/test/groovy/io/jsonwebtoken/lang/CollectionsTest.groovy, impl/src/main/java/io/jsonwebtoken/impl/DefaultClaims.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultJweHeaderMutator.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParser.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParserBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/DelegatingClaimsMutator.java, impl/src/main/java/io/jsonwebtoken/impl/FieldMap.java, impl/src/main/java/io/jsonwebtoken/impl/lang/Fields.java, impl/src/main/java/io/jsonwebtoken/impl/security/DefaultJwkContext.java, impl/src/test/groovy/io/jsonwebtoken/JwtParserTest.groovy, impl/src/test/groovy/io/jsonwebtoken/JwtsTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtBuilderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/AbstractJwkBuilderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/EdSignatureAlgorithmTest.groovy, impl/src/test/groovy/io/jsonwebtoken/issues/Issue438Test.groovy, tdjar/src/test/java/io/jsonwebtoken/all/JavaReadmeTest.java
Closes #77 
Ensured the `aud` claim is a `Set<String>` by default (which serializes as a JSON Array), but allows a single string value on creation for recipients that do not understand `aud` JSON Array values:
- `ClaimsMutator#audience(String)` now appends to the `aud` set, and may be called multiple times
- Added new `ClaimsMutator#audience(Collection)` method for setting/full replacement of the `aud` set
- Added new `ClaimsMutator#audienceSingle` for setting/full replacement of single string value
- `Claims#getAudience()` is now a `Set<String>` so application developers never need to deal with type checking/conversion.  If a single string (non JSON Array) `aud` claim exists, it is converted to a single-element `Set<String>` first.
The name `audienceSingle` was chosen over (the more …
=> Audience claim string arrays

impl/src/main/java/io/jsonwebtoken/impl/lang/Bytes.java, impl/src/main/java/io/jsonwebtoken/impl/lang/Fields.java, impl/src/main/java/io/jsonwebtoken/impl/security/AbstractJwk.java, impl/src/main/java/io/jsonwebtoken/impl/security/AbstractJwkBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/security/AbstractPrivateJwk.java, impl/src/main/java/io/jsonwebtoken/impl/security/AbstractPublicJwk.java, impl/src/main/java/io/jsonwebtoken/impl/security/DefaultEcPrivateJwk.java, impl/src/main/java/io/jsonwebtoken/impl/security/DefaultEcPublicJwk.java, impl/src/main/java/io/jsonwebtoken/impl/security/DefaultMacAlgorithm.java, impl/src/main/java/io/jsonwebtoken/impl/security/DefaultOctetPrivateJwk.java, impl/src/main/java/io/jsonwebtoken/impl/security/DefaultOctetPublicJwk.java, impl/src/main/java/io/jsonwebtoken/impl/security/DefaultRsaPrivateJwk.java, impl/src/main/java/io/jsonwebtoken/impl/security/DefaultRsaPublicJwk.java, impl/src/main/java/io/jsonwebtoken/impl/security/DefaultSecretJwk.java, impl/src/test/groovy/io/jsonwebtoken/impl/AbstractProtectedHeaderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJweHeaderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/lang/BytesTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/lang/FieldsTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/lang/RedactedSupplierTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/lang/TestFieldReadable.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/AbstractJwkTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/DefaultRsaPrivateJwkTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/JwksTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/SecretJwkFactoryTest.groovy
- Adjusted JWK .equals implementatinos to only account for `kty` value and material fields (two JWKs are equal if their type and key material are equal, regardless of other public parameters and/or custom name/value pairs).
- Adjusted JWK .hashCode implementation to pre-cache its value based on JwkThumpbrint fields since JWKs are immutable
=> JWK .equals and .hashCode

README.md, api/src/main/java/io/jsonwebtoken/ClaimsMutator.java, api/src/main/java/io/jsonwebtoken/JwtParserBuilder.java, api/src/main/java/io/jsonwebtoken/ProtectedHeaderMutator.java, api/src/main/java/io/jsonwebtoken/lang/Collections.java, api/src/main/java/io/jsonwebtoken/security/JwkBuilder.java, api/src/test/groovy/io/jsonwebtoken/lang/CollectionsTest.groovy, impl/src/main/java/io/jsonwebtoken/impl/DefaultJweHeaderMutator.java, impl/src/main/java/io/jsonwebtoken/impl/DelegatingClaimsMutator.java, impl/src/main/java/io/jsonwebtoken/impl/security/AbstractJwkBuilder.java, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtBuilderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtHeaderBuilderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/JwksTest.groovy
Ensured various builder collection argument methods were semantically the same (append operations, not one append, one replace)
=> Builder collection method semantics

impl/src/main/java/io/jsonwebtoken/impl/lang/Services.java, impl/src/test/groovy/io/jsonwebtoken/impl/lang/ServicesTest.groovy
The first ServiceLoaders found when looking up a class will be cached. This cache can be reset by calling `Services.reload()`, to help
facilitate testing or instances where a classpaths are dynamically changed at runtime.
Fixes: #752
=> ServiceLoaders are now cached.

.github/workflows/ci.yml, pom.xml
* Update groovy patch version to support Java 21.
NOTE: This adds a Maven profile that ups the source/target version to Java 8, but ONLY when building with 21+
=> Add Java 21 to CI matrix build

api/src/main/java/io/jsonwebtoken/lang/Objects.java, impl/src/main/java/io/jsonwebtoken/impl/ParameterMap.java, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtBuilderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/issues/Issue858Test.groovy
Custom claims can now be empty again (behavior for <= 0.11.5).
=> Closes #858.

extensions/orgjson/src/main/java/io/jsonwebtoken/orgjson/io/OrgJsonDeserializer.java, extensions/orgjson/src/test/groovy/io/jsonwebtoken/orgjson/io/OrgJsonDeserializerTest.groovy
OrgJsonDeserializer: Added fallback implementation for Android when `JSONTokener(Reader)` constructor is not available.
Closes #882
=> JSONTokener constructor fallback

CHANGELOG.md, impl/src/main/java/io/jsonwebtoken/impl/DelegatingClaimsMutator.java, impl/src/test/groovy/io/jsonwebtoken/JwtsTest.groovy
Ensured a single string `aud` (Audience) claim would be retained (without converting it to a `Set`) when copying/applying a source Claims instance to a destination Claims builder.
Updated CHANGELOG.md accordingly.
Fixes #890.
=> Audience single string claim data type retention when copying

impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParserBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/io/AbstractParserBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/lang/Services.java, impl/src/main/java/io/jsonwebtoken/impl/security/JwksBridge.java, impl/src/test/groovy/io/jsonwebtoken/JwtsTest.groovy, impl/src/test/groovy/io/jsonwebtoken/RFC7515AppendixETest.groovy, impl/src/test/groovy/io/jsonwebtoken/RFC7797Test.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtBuilderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtParserTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/RfcTests.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/lang/ServicesTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/RFC7518AppendixCTest.groovy
Blend of pre-0.11.0 behavior that cached implementation instances and post-0.11.0 behavior using the JDK ServiceLoader to find/create instances of an SPI interface.  This change:
- Reinstates the <= 0.10.x behavior of caching application singleton service implementation instances in a thread-safe reference (previously an `AtomicReference`, but in this change, a `ConcurrentMap`).  If an app singleton instance is cached and found, it is returned to be (re)used immediately when requested.  This is ok for JJWT's purposes because all service implementations instances must be thread-safe application singletons by API contract/design, so caching them for repeated use is fine.
- Ensures that only if a service implementation instance is not in the app singleton cache, a new instance is …
=> Thread-safe ServiceLoader usage

extensions/jackson/src/main/java/io/jsonwebtoken/jackson/io/JacksonDeserializer.java, extensions/jackson/src/main/java/io/jsonwebtoken/jackson/io/JacksonSerializer.java, extensions/jackson/src/test/groovy/io/jsonwebtoken/jackson/io/JacksonDeserializerTest.groovy
- Ensures that Jackson duplicate property detection/rejection is enabled by default.
Fixes #877
=> Jackson: disallow duplicate JSON properties

README.md
All of Stormpath.com consistently responds with 404 ATM, therefore this commit replaces the links with archive.org versions that will hopefully stay available for good.
=> Fix broken links in "Learn more" section

CHANGELOG.md, impl/src/main/java/io/jsonwebtoken/impl/lang/Bytes.java, impl/src/main/java/io/jsonwebtoken/impl/security/AbstractEcJwkFactory.java, impl/src/main/java/io/jsonwebtoken/impl/security/DefaultEcPrivateJwk.java, impl/src/main/java/io/jsonwebtoken/impl/security/DefaultEcPublicJwk.java, impl/src/main/java/io/jsonwebtoken/impl/security/EcPrivateJwkFactory.java, impl/src/main/java/io/jsonwebtoken/impl/security/EcPublicJwkFactory.java, impl/src/main/java/io/jsonwebtoken/impl/security/FieldElementConverter.java, impl/src/test/groovy/io/jsonwebtoken/impl/security/AbstractEcJwkFactoryTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/DispatchingJwkFactoryTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/FieldElementConverterTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/RFC7517AppendixA2Test.groovy
Ensured NIST Elliptic Curve JWK `x`, `y` and `d` byte array values are padded with leading zero (`0x00`) bytes if necessary before Base64URL-encoding per length requirements defined in:
- https://datatracker.ietf.org/doc/html/rfc7518#section-6.2.1.2
- https://datatracker.ietf.org/doc/html/rfc7518#section-6.2.1.3
- https://datatracker.ietf.org/doc/html/rfc7518#section-6.2.2.1
Fixes #901.
=> NIST Elliptic Curve JWKs: field element byte array padding

extensions/jackson/src/main/java/io/jsonwebtoken/jackson/io/JacksonSerializer.java, extensions/jackson/src/test/groovy/io/jsonwebtoken/jackson/io/JacksonDeserializerTest.groovy
In order to disable Jackson `ObjectMapper` `FAIL_ON_UNKNOWN_PROPERTIES` Deserialization Feature by default , Edit static `newObjectMapper` method of `JacksonSerializer`:
```
static ObjectMapper newObjectMapper() {
return new ObjectMapper()
.registerModule(MODULE)
.configure(JsonParser.Feature.STRICT_DUPLICATE_DETECTION, true) // https://github.com/jwtk/jjwt/issues/877
.configure(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES, false); // https://github.com/jwtk/jjwt/issues/893
}
```
**Also add specific test with `json` which has unknown field and must seserialize to custom data type.**
This PR fixs #893 
Note:
I close #894 PR and reopen this PR, because it has confilict with synchronous and same changes in #895 PR of @lhazlewood
=> #893 Disable Jackson ObjectMapper FAIL_ON_UNKNOWN_PROPERTIES Deserialization Feature by default

impl/src/test/groovy/io/jsonwebtoken/impl/security/AbstractEcJwkFactoryTest.groovy
to be based on the curve order (not the field size) per https://datatracker.ietf.org/doc/html/rfc7518#section-6.2.2.1.  Minor addendum to #903
=> Minor test change to reflect correct assertion for JWK Elliptic Curve 'd' byte array values

CHANGELOG.md, impl/src/main/java/io/jsonwebtoken/impl/security/AesAlgorithm.java, impl/src/main/java/io/jsonwebtoken/impl/security/SecretJwkFactory.java, impl/src/test/groovy/io/jsonwebtoken/impl/security/AbstractJwkBuilderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/JwkSerializationTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/JwksTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/SecretJwkFactoryTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/TestKeys.groovy
- Ensured Secret JWK 'k' byte arrays for HMAC-SHA algorithms can be larger than the identified HS* algorithm. This is allowed per https://datatracker.ietf.org/doc/html/rfc7518#section-3.2: "A key of the same size as the hash output ... _or larger_ MUST be used with this algorithm"
- Ensured that, when using the JwkBuilder, Secret JWK 'alg' values would automatically be set to 'HS256', 'HS384', or 'HS512' if the specified Java SecretKey algorithm name equals a JCA standard name (HmacSHA256, HmacSHA384, etc) or JCA standard HMAC-SHA OID.
-  Updated CHANGELOG.md accordingly.
Fixes #901.
=> Secret JWK `k` values larger than HMAC-SHA minimums

.github/workflows/ci.yml
Updating to GitHub latest actions/checkout and actions/setup-java script versions due to Node.js 16 deprecation warnings in the GH Actions tab when viewing a build/run
=> GitHub Actions workflow cleanup

CHANGELOG.md, impl/src/main/java/io/jsonwebtoken/impl/security/Pbes2HsAkwAlgorithm.java, impl/src/test/groovy/io/jsonwebtoken/impl/security/Pbes2HsAkwAlgorithmTest.groovy
Ensured there is an upper bound (maximum) iterations enforced for PBES2 decryption to help mitigate potential DoS attacks. 
Many thanks to Jingcheng Yang and Jianjun Chen from Sichuan University and Zhongguancun Lab for their work on this!
=> PBES2 decryption maximum iterations

CHANGELOG.md, README.md, api/src/main/java/io/jsonwebtoken/ClaimsMutator.java, api/src/main/java/io/jsonwebtoken/JwtParserBuilder.java, api/src/main/java/io/jsonwebtoken/ProtectedHeaderMutator.java, api/src/main/java/io/jsonwebtoken/lang/NestedCollection.java, api/src/main/java/io/jsonwebtoken/security/JwkBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultJweHeaderMutator.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParserBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/DelegatingClaimsMutator.java, impl/src/main/java/io/jsonwebtoken/impl/lang/DefaultCollectionMutator.java, impl/src/main/java/io/jsonwebtoken/impl/security/AbstractJwkBuilder.java, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtBuilderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtHeaderBuilderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtParserBuilderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/lang/DefaultCollectionMutatorTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/AbstractJwkBuilderTest.groovy
* Ensured `NestedCollection`s do not need their `.and()` method called to apply collection changes. Instead, changes are applied immediately as they occur (via `.add`, `.remove`, etc), and `.and()` is now purely for returning to the parent builder if necessary/desired.
* Updated associated JavaDoc with code examples to make the `.and()` method's purpose a little clearer.
* Updated CHANGELOG.md
Closes #916
=> NestedCollection changes without `.and()`

impl/src/main/java/io/jsonwebtoken/impl/security/DefaultMacAlgorithm.java, impl/src/main/java/io/jsonwebtoken/impl/security/KeysBridge.java, impl/src/test/groovy/io/jsonwebtoken/impl/security/DefaultMacAlgorithmTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/KeysBridgeTest.groovy
Extend the pre-existing check for SUN PKCS11 generic secret to allow all SecretKeys where getAlgorithm() returns "GenericSecret" to bypass the algorithm validation.
This matches at least with AWS CloudHSM JCE provider, but likely others as well.
Relates to discussion https://github.com/jwtk/jjwt/discussions/934
Let me know if more tests are needed. I didn't find a test that would've tested the existing Sun PKCS#11 generic secret case, and not sure how to test that when the class doesn't exist in the classpath.
=> Allow using GenericSecret for HmacSHA*

impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtBuilder.java, impl/src/test/groovy/io/jsonwebtoken/JwtsTest.groovy
The JWE content was compressed only when claims was used as payload, but when using arbitrary content string/bytes/input stream, the compression was omitted, while keeping the "zip" header field, leading to un-parseable JWE as the decompression failed on non-compressed content.
I couldn't find any evidence that this was intended behavior from the documentation or the JWE spec, so made a fix for this.
See https://github.com/jwtk/jjwt/discussions/936
Note that people might have used a similar workaround as I presented in the discussion to manually compress the payload, so fixing this might result in some code breaking somewhere. Might be good to mention in the changelog.
=> JWE arbitrary content compression

CHANGELOG.md, README.adoc, api/pom.xml, extensions/gson/pom.xml, extensions/jackson/pom.xml, extensions/orgjson/pom.xml, extensions/pom.xml, impl/pom.xml, pom.xml, tdjar/pom.xml
Merging release branch into main
=> 0.12.6 release

bom/pom.xml, pom.xml
Adds a Maven BOM to the project for publication to Maven central. Fixes #967.
=> Add Maven BOM 

.github/workflows/ci.yml
Changing JDK 17 build to use GitHub's `setup-java` action instead of Oracle's due to failing Oracle JDK 17 download.
Resolves #980.
=> Use GitHub setup-java for JDK 17

.github/workflows/ci.yml, pom.xml
This replaces the custom name with an SPDX identifier to enable tooling to automatically detect the correct license. Using an SPDX identifier is recommended [by the official Maven documentation](https://maven.apache.org/pom.html#Licenses).
See https://spdx.org/licenses/Apache-2.0.html
=> Use SPDX identifier in POMs

CHANGELOG.md, impl/src/main/java/io/jsonwebtoken/impl/security/DefaultJwkSet.java, impl/src/main/java/io/jsonwebtoken/impl/security/JwkSetConverter.java, impl/src/test/groovy/io/jsonwebtoken/impl/security/DefaultJwkSetBuilderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/security/DefaultJwkSetTest.groovy
Ensured JwkSet `keys` parameter is not `secret` by default.  Each JWK element should determine which members are secret or not.
Resolves #976.
=> JwkSet keys secrecy default

CHANGELOG.md, api/src/main/java/io/jsonwebtoken/Jwts.java, api/src/main/java/io/jsonwebtoken/security/Jwks.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultClaimsBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtHeaderBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParserBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/security/DefaultDynamicJwkBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/security/DefaultJwkParserBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/security/DefaultJwkSetBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/security/DefaultJwkSetParserBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/security/DefaultKeyOperationBuilder.java, impl/src/main/java/io/jsonwebtoken/impl/security/DefaultKeyOperationPolicyBuilder.java
Ensured `*Builder` instances are no longer created with reflection using `Classes.newInstance`.  Instead, `Classes.newInstance` is used to create static/thread-safe Supplier singletons when the api module is loaded, and those singletons will directly instantiate `*Builder` instances at runtime using the `new` keyword`.
Resolves #988.
=> Ensured *Builder instances are no longer created with reflection 

impl/src/test/groovy/io/jsonwebtoken/impl/security/Pkcs11Test.groovy, impl/src/test/scripts/softhsm
After upgrading homebrew to openssl 3, softhsm logins were failing on MacOS 10.14.  Upgrading to Sonoma (10.15.6), it still failed. Completely deleting and reinstalling XCode Command Line tools didn't work.  Finally, a custom build from source worked per https://github.com/parallaxsecond/rust-cryptoki/issues/191.
This PR updates the softhsm-related code to work on a system with a source build.
=> Ensure softhsm worked with local build from source

impl/src/main/java/io/jsonwebtoken/impl/DefaultHeader.java, impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParser.java, impl/src/main/java/io/jsonwebtoken/impl/IdLocator.java, impl/src/main/java/io/jsonwebtoken/impl/lang/DefaultRegistry.java, impl/src/main/java/io/jsonwebtoken/impl/lang/IdRegistry.java, impl/src/main/java/io/jsonwebtoken/impl/lang/StringRegistry.java, impl/src/test/groovy/io/jsonwebtoken/JwtParserTest.groovy, impl/src/test/groovy/io/jsonwebtoken/JwtsTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtParserBuilderTest.groovy, impl/src/test/groovy/io/jsonwebtoken/impl/IdLocatorTest.groovy
Resolves #996.
Allowed the `JwtParser` to have empty nested algorithm collections, effectively disabling the parser's associated feature:
- Clearing the `zip()` nested collection means parser decompression is disabled
- Clearing the `sig()` nested collection means parser signature verification is disabled (i.e. all JWSs will be unsupported/rejected)
- Clearing the `enc()` or `key()` nested collections means parser decryption is disabled (i.e. all JWEs will be unsupported/rejected)
=> Enable JwtParser empty nested algorithm collections.
