- README.md
- src/main/java/io/jsonwebtoken/ClaimJwtException.java
- src/main/java/io/jsonwebtoken/Claims.java
- src/main/java/io/jsonwebtoken/IncorrectClaimException.java
- src/main/java/io/jsonwebtoken/InvalidClaimException.java
- src/main/java/io/jsonwebtoken/JwtParser.java
- src/main/java/io/jsonwebtoken/MissingClaimException.java
- src/main/java/io/jsonwebtoken/RequiredTypeException.java
- src/main/java/io/jsonwebtoken/impl/DefaultClaims.java
- src/main/java/io/jsonwebtoken/impl/DefaultJwtParser.java
- src/test/groovy/io/jsonwebtoken/IncorrectClaimExceptionTest.groovy
- src/test/groovy/io/jsonwebtoken/InvalidClaimExceptionTest.groovy
- src/test/groovy/io/jsonwebtoken/JwtParserTest.groovy
- src/test/groovy/io/jsonwebtoken/MissingClaimExceptionTest.groovy
- src/test/groovy/io/jsonwebtoken/RequiredTypeExceptionTest.groovy
- src/test/groovy/io/jsonwebtoken/impl/DefaultClaimsTest.groovy
- src/test/groovy/io/jsonwebtoken/impl/JwtMapTest.groovy
> Issue 42 assert claims new

- pom.xml
Resolves #100 
Merged master into PR #95
> Enabled OSGi bundle

- pom.xml
> Upgraded Jackson to 2.7.0

- src/main/java/io/jsonwebtoken/impl/crypto/MacProvider.java
Updated the number of bits for the HS512 algorithm in the javadoc comment.
> javadoc typo

- .travis.yml
- pom.xml
per: https://github.com/trautonen/coveralls-maven-plugin#faq
> updated to jacoco as only jacoco supports java 8

- .gitignore
> add eclipse files to gitignore

- pom.xml
- src/test/groovy/io/jsonwebtoken/JwtParserTest.groovy
> 161: upgraded library versions to latest stable

- src/main/java/io/jsonwebtoken/impl/DefaultJwtParser.java
- src/test/groovy/io/jsonwebtoken/JwtParserTest.groovy
> 107: ensured exception message printed UTC times correctly

- src/main/java/io/jsonwebtoken/JwtParser.java
> Removed redundant/incorrect docs

- pom.xml
Addresses Jackson Deserializer security vulnerability: FasterXML/jackson-databind#1599
> Update jackson.version to 2.8.9

- .travis.yml
- README.md
- pom.xml
- src/main/java/io/jsonwebtoken/Header.java
- src/main/java/io/jsonwebtoken/JwtBuilder.java
- src/main/java/io/jsonwebtoken/JwtParser.java
- src/main/java/io/jsonwebtoken/impl/DefaultJwtBuilder.java
- src/main/java/io/jsonwebtoken/impl/crypto/EllipticCurveSigner.java
- src/test/groovy/io/jsonwebtoken/impl/DefaultJwtBuilderTest.groovy
- src/test/groovy/io/jsonwebtoken/impl/crypto/EllipticCurveSignerTest.groovy
Merge latest master as well.
The *actual* changed files are:
`src/main/java/io/jsonwebtoken/Header.java`
`src/main/java/io/jsonwebtoken/JwtBuilder.java`
> Minor punctuation and sentence structure updates. Changed Json to JSON per spec.

- README.md
Add Proguard rules for Android projects so it can be referenced right away.
> Add Proguard setup section on README

- pom.xml
- src/main/java/io/jsonwebtoken/impl/DefaultClaims.java
- src/main/java/io/jsonwebtoken/impl/DefaultJwtParser.java
- src/main/java/io/jsonwebtoken/impl/JwtMap.java
- src/main/java/io/jsonwebtoken/io/DeserializationException.java
- src/main/java/io/jsonwebtoken/io/IOException.java
- src/main/java/io/jsonwebtoken/io/SerialException.java
- src/main/java/io/jsonwebtoken/io/SerializationException.java
- src/main/java/io/jsonwebtoken/io/impl/RuntimeClasspathDeserializerLocator.java
- src/main/java/io/jsonwebtoken/io/impl/RuntimeClasspathSerializerLocator.java
- src/main/java/io/jsonwebtoken/io/impl/orgjson/OrgJsonDeserializer.java
- src/main/java/io/jsonwebtoken/io/impl/orgjson/OrgJsonSerializer.java
- src/main/java/io/jsonwebtoken/lang/DateFormats.java
- src/test/groovy/io/jsonwebtoken/JwtParserTest.groovy
- src/test/groovy/io/jsonwebtoken/JwtsTest.groovy
- src/test/groovy/io/jsonwebtoken/impl/DefaultJwtBuilderTest.groovy
- src/test/groovy/io/jsonwebtoken/impl/DefaultJwtParserTest.groovy
- src/test/groovy/io/jsonwebtoken/impl/JwtMapTest.groovy
- src/test/groovy/io/jsonwebtoken/io/impl/RuntimeClasspathDeserializerLocatorTest.groovy
- src/test/groovy/io/jsonwebtoken/io/impl/RuntimeClasspathSerializerLocatorTest.groovy
- src/test/groovy/io/jsonwebtoken/io/impl/jackson/JacksonSerializerTest.groovy
- src/test/groovy/io/jsonwebtoken/io/impl/orgjson/OrgJsonDeserializerTest.groovy
- src/test/groovy/io/jsonwebtoken/io/impl/orgjson/OrgJsonSerializerTest.groovy
org.json support with 100% test coverage
> org.json support

- api/src/main/java/io/jsonwebtoken/lang/DateFormats.java
- api/src/test/groovy/io/jsonwebtoken/lang/DateFormatsTest.groovy
> Fix claim assertion exception message to reflect UTC timestamps

- api/src/main/java/io/jsonwebtoken/io/Base64.java
- api/src/main/java/io/jsonwebtoken/io/CodecException.java
- api/src/main/java/io/jsonwebtoken/io/DecodingException.java
- api/src/test/groovy/io/jsonwebtoken/io/Base64Test.groovy
Implementation with tests.  Resolves #285
> Descriptive exception when decoding illegal Base64(Url) input

- api/src/main/java/io/jsonwebtoken/io/Base64.java
#285: added throws clause and updated javadoc
> Base64 update throws clause

- CHANGELOG.md
- README.md
- api/src/main/java/io/jsonwebtoken/security/Keys.java
> Documentation revamp

- api/src/main/java/io/jsonwebtoken/JwtBuilder.java
> Fix JwtBuilder javadoc - resolves #386

- CHANGELOG.md
- impl/src/main/java/io/jsonwebtoken/impl/compression/AbstractCompressionCodec.java
- impl/src/main/java/io/jsonwebtoken/impl/compression/DeflateCompressionCodec.java
- impl/src/main/java/io/jsonwebtoken/impl/compression/GzipCompressionCodec.java
Also refactored `GzipCompressionCodec` and `AbstractCompressionCodec` to utilize consistent logic across compression algorithms.  Resolves #392.
> Refactored DeflateCompressionCodec to eliminate memory leak.  

- README.md
> Issue 449: updated docs to better clarify help and contributing.

- api/pom.xml
- extensions/gson/pom.xml
- extensions/jackson/pom.xml
- extensions/orgjson/pom.xml
- extensions/pom.xml
- impl/pom.xml
- pom.xml
that require a minor semantic version increment (Issue #410)
> Incrementing minor version snapshot to reflect new features in master

- pom.xml
> Reenable using the manifest from maven-bundle-plugin run

- pom.xml
Merge japicmp plugin definitions - caused by a merge
> Fix duplicate japicmp plugin definition in root pom

- README.md
> Docs: Adds section to README covering custom object parsing

- impl/src/test/groovy/io/jsonwebtoken/DateTestUtils.groovy
- impl/src/test/groovy/io/jsonwebtoken/DeprecatedJwtParserTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/JwtParserTest.groovy
A long was being treated as a float
> Fixes test error caused by groovy type coercion

- api/pom.xml
- extensions/gson/pom.xml
- extensions/jackson/pom.xml
- extensions/orgjson/pom.xml
- extensions/pom.xml
- impl/pom.xml
- pom.xml
via: `mvn versions:set -DnewVersion=0.11.0-SNAPSHOT -DgenerateBackupPoms=false`
> Update version to 0.11.0-SNAPSHOT

- CHANGELOG.md
- README.md
- api/src/main/java/io/jsonwebtoken/JwtParserBuilder.java
- api/src/main/java/io/jsonwebtoken/Jwts.java
> Docs: Add note about JwtParserBuilder creating an immutable JwtParser

- impl/src/main/java/io/jsonwebtoken/impl/crypto/RsaSignatureValidator.java
> Update SignatureValidator to use MessageDigest

- README.md
> Documented how to convert strings to SecretKey instances.

- CHANGELOG.md
- api/src/main/java/io/jsonwebtoken/Claims.java
> Minor JavaDoc fix

- CHANGELOG.md
> Documented jackson upgrade in changelog

- CHANGELOG.md
- api/src/main/java/io/jsonwebtoken/lang/Maps.java
> Add parameterized return type to Maps.and()

- impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParserBuilder.java
This addresses a potential service loader issue with OSGi runtimes.
> Removes eager initialization of the CompressionCodecResolver in the JwtParserBuilder

- CHANGELOG.md
Add notes about Jackson version update in release notes: #642
> Start release notes for 0.11.3

- CHANGELOG.md
- pom.xml
Fixes: #716
Fixes: #614
Fixes: #696
> Update Jackson Databind to 2.12.6.1

- api/src/main/java/io/jsonwebtoken/JwtParserBuilder.java
> Missing JwtParserBuilder method deprecation annotation

- CHANGELOG.md
- README.md
- api/pom.xml
- extensions/gson/pom.xml
- extensions/jackson/pom.xml
- extensions/orgjson/pom.xml
- extensions/pom.xml
- impl/pom.xml
- pom.xml
- Updated README.md version numbers to reflect the upcoming 0.11.4 release
- Added 0.11.4 release/changelog notes
> Prep for 0.11.4 release

- impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParser.java
- impl/src/main/java/io/jsonwebtoken/impl/FixedClock.java
- impl/src/test/groovy/io/jsonwebtoken/JwtParserTest.groovy
Instead of now + skew - expired
Fixes: #660
> JWT expired exception is now shows difference as now - expired

- api/src/main/java/io/jsonwebtoken/security/Keys.java
Related issue #764 
EC256 > ES256
EC384 > ES384
EC512 > ES512
> Changed some javadoc typos

- .github/workflows/ci.yml
closed: #799 
I replace duplicate code with global environment variable
reference1 : https://github.com/kubernetes/minikube/blob/master/.github/workflows/pr.yml#L13-L15
reference2 : https://github.com/yorkie-team/yorkie/blob/main/.github/workflows/ci.yml#L9-L10
I'm so glad to be able to contribute to this 😍
> Replace duplicate code with global environment variable

- impl/src/test/groovy/io/jsonwebtoken/issues/Issue438Test.groovy
> Added test case for #438

- pom.xml
> Upgraded org.json dependency to latest available version 20230618

- api/src/main/java/io/jsonwebtoken/security/UnsupportedKeyException.java
- impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParserBuilder.java
- impl/src/main/java/io/jsonwebtoken/impl/security/DefaultDynamicJwkBuilder.java
- impl/src/main/java/io/jsonwebtoken/impl/security/DefaultMacAlgorithm.java
- impl/src/main/java/io/jsonwebtoken/impl/security/DefaultRsaKeyAlgorithm.java
- impl/src/main/java/io/jsonwebtoken/impl/security/EcPrivateJwkFactory.java
- impl/src/main/java/io/jsonwebtoken/impl/security/EcPublicJwkFactory.java
- impl/src/main/java/io/jsonwebtoken/impl/security/EcSignatureAlgorithm.java
- impl/src/main/java/io/jsonwebtoken/impl/security/EcdhKeyAlgorithm.java
- impl/src/main/java/io/jsonwebtoken/impl/security/EdSignatureAlgorithm.java
- impl/src/main/java/io/jsonwebtoken/impl/security/EdwardsCurve.java
- impl/src/main/java/io/jsonwebtoken/impl/security/EdwardsPublicKeyDeriver.java
- impl/src/main/java/io/jsonwebtoken/impl/security/KeysBridge.java
- impl/src/main/java/io/jsonwebtoken/impl/security/OctetJwkFactory.java
- impl/src/main/java/io/jsonwebtoken/impl/security/RsaPrivateJwkFactory.java
- impl/src/main/java/io/jsonwebtoken/impl/security/RsaSignatureAlgorithm.java
- impl/src/main/java/io/jsonwebtoken/impl/security/SecretJwkFactory.java
- impl/src/test/groovy/io/jsonwebtoken/JwtsTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtParserBuilderTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/security/DefaultMacAlgorithmTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/security/DefaultRsaKeyAlgorithmTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/security/EcPrivateJwkFactoryTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/security/EcPublicJwkFactoryTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/security/EcSignatureAlgorithmTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/security/EcdhKeyAlgorithmTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/security/EdwardsCurveTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/security/EdwardsPublicKeyDeriverTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/security/JwksTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/security/RsaPrivateJwkFactoryTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/security/RsaSignatureAlgorithmTest.groovy
for more cohesive delineation between "I don't know what this is" vs "this is invalid and cannot be used"
> UnsupportedKeyException changes

- api/src/main/java/io/jsonwebtoken/JwtParserBuilder.java
- api/src/main/java/io/jsonwebtoken/ProtectedHeader.java
- api/src/main/java/io/jsonwebtoken/lang/Collections.java
- api/src/test/groovy/io/jsonwebtoken/lang/CollectionsTest.groovy
- impl/src/main/java/io/jsonwebtoken/impl/DefaultJweHeader.java
- impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtBuilder.java
- impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtHeaderBuilder.java
- impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParser.java
- impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParserBuilder.java
- impl/src/main/java/io/jsonwebtoken/impl/DefaultProtectedHeader.java
- impl/src/main/java/io/jsonwebtoken/impl/lang/RequiredParameterReader.java
- impl/src/test/groovy/io/jsonwebtoken/RFC7515AppendixETest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/AbstractProtectedHeaderTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtHeaderBuilderTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtParserBuilderTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtParserTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/IdLocatorTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/security/AesGcmKeyAlgorithmTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/security/EcdhKeyAlgorithmTest.groovy
Per the rules defined in https://www.rfc-editor.org/rfc/rfc7515.html#section-4.1.11
> Support `crit` header enforcement

- impl/src/main/java/io/jsonwebtoken/impl/DefaultJwtParser.java
- impl/src/test/groovy/io/jsonwebtoken/JwtParserTest.groovy
- impl/src/test/groovy/io/jsonwebtoken/impl/DefaultJwtParserTest.groovy
Fixed exception message per recommendation.
Also updated expiration message to be clearer/intuitive.
> Closes #816

- impl/src/main/java/io/jsonwebtoken/impl/lang/UnavailableImplementationException.java
Fixed exception message per recommendation.
> Closes #773

- README.md
This PR just fixes some small typos at README.md :)
> Fix small typos at README.md

- README.md
Added JWK Set documentation to README.md
> Added JWK Set documentation to README.mdJwkset doc

- api/src/main/java/io/jsonwebtoken/lang/Collections.java
Fixes https://github.com/jwtk/jjwt/issues/965
> Return immutable Set for a Collection

- extensions/jackson/src/main/java/io/jsonwebtoken/jackson/io/JacksonDeserializer.java
> Made constructor public to allow users their own objectMapper instance
